sonar.projectKey=rahaf511511_8.2CDevSecOps
sonar.organization=rahaf511511
sonar.host.url=https://sonarcloud.io

sonar.sources=.
sonar.exclusions=**/node_modules/**,**/*.js,**/*.jsx,**/*.ts,**/*.tsx,public/**,views/**

sonar.c.file.suffixes=-
sonar.cpp.file.suffixes=-
sonar.objc.file.suffixes=-

sonar.sourceEncoding=UTF-8
